import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Card } from "@mui/material";
//
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coilboss</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://www.instagram.com/_coilboss/">Coilboss</a>
        </h1>

        <p className={styles.description}>Some text here </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Instagram </h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>YouTube </h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples </h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy </h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
